Add dev site to readme
dog-house-development/poodl pull request #105
Opened 2019-02-08 15:40 UTC by sambehrens

2019-02-08 20:22 UTC, karlmolina requested changes

2019-02-08 20:22 UTC, karlmolina commented on README.md
> +**prod:** [poodl.herokuapp.com](http://poodl-dev.herokuapp.com/)
write out production

2019-02-08 20:22 UTC, karlmolina commented on README.md
> +**dev:** [poodl-dev.herokuapp.com](http://poodl-dev.herokuapp.com/)
write out development

2019-02-08 21:01 UTC, sambehrens commented on README.md
> +**prod:** [poodl.herokuapp.com](http://poodl-dev.herokuapp.com/)
Done

2019-02-08 21:01 UTC, sambehrens commented on README.md
> +**dev:** [poodl-dev.herokuapp.com](http://poodl-dev.herokuapp.com/)
Done

2019-02-09 01:04 UTC, karlmolina approved these changes

2019-02-09 01:04 UTC, merged